sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_script:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  on:
    tags: true
    repo: Eyevinn/hls-ts-js
  api_key:
    secure: oL8Bpx08k+gy0jFMIkxCjR28T+qPiQhBKZK+QarxfMzJ9c7It2Hq/sHLVXR4MtYeWTpNKDJ4o9GRjpc/rS3c4yYUuTSiSODtAjS8izpM9BriV2btFy3cHucBFjdQSjU+1h2Txf6o1iXoieNOs9thcPpKn5t06S4/m+Fep3BpLI1RqZVpsppA1XyVx/5+KcW/0Q6iPxt27dq/UoC9e4P0amoHXHxTLNxAzqusa2BNehZ5mtHVKXmbQ71wsy3kOpAtXKKdzOdxpcnZqty/8tu2TOHVf2jncWFfKrqc6F/GSRs51/8BV4izT2HT8SJX7HWv4yCAyDpCA76cgOTYqqh2S5YLak6TlGeyNmtnZHn8tVTi8DYsN+nPEkgvOZksT6TjCRIKFEmhJv//0LTcuCFhQCSGCzLAZM/dplp25JrzL2y+Wy7rchtz8M+NzRSkjLs+ptnZNyHdHtAyMfBThp2nk4WJs+deRkV3Luv+O2Q+TcekAXDxKSAqJ2iibe6mL4gHN11PocxhkcKWt/6N8gb9dLXtd5kPYhSLJkP23eDJkwDhIXbQdQGkdBkSSpvcIdwU19GEIGasMZpUtJNTPJX7p0d9Shx+88qSGf1qc6o1xuhSR2Rk/1I39upUzX/kFylrghnsdz78POhMuHS0jvkwvqsX3ofZqfmbOQo77SGY/ic=
